In [1]:
## Tim Day
## 862016623
## Team JellyBean

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
# get url
nasdaq_top_100 = requests.get('https://www.stockmonitor.com/nasdaq-stocks/')

# parse with BS4
soup = BeautifulSoup(nasdaq_top_100.content,"html.parser")

# pull data for columns
tmp_lst=[]
for row in soup.table.find_all('tr')[1:]:
    r_td = row.find_all('td')
    f=[]
    for obj in r_td:
        temp = obj.text.replace("\n","")
        f.append(temp.replace(" ",""))
    tmp_lst.append(f)
    
# create dataframe
df = pd.DataFrame(data = tmp_lst, columns = ["change","symbol","name","price","volume","high","low"])

# clean dataframe
df['high'] = df['high'].str.replace(',','')
df['high'] = df['high'].str.replace('\r','')
df['low'] = df['low'].str.replace(',','')
df['low'] = df['low'].str.replace('\r','')
df['price'] = df['price'].str.replace(',','')
df['price'] = df['price'].str.replace('\r','')
df['volume'] = df['volume'].str.replace('\r', '')
df['volume'] = df['volume'].str.replace(',', '')
df['name'] = df['name'].str.replace('\r', '')
df['change'] = df['change'].str[1:-1].astype(float)

# specify types
df['high'] = df['high'].astype('float')
df['low'] = df['low'].astype('float')
df['price'] = df['price'].astype('float')
df['volume'] = df['volume'].astype('int')

# set symbol as index
df.set_index('symbol',inplace=True)

# save to csv
df.to_csv('./data_files/nasdaq_top_100.csv')

df.head(5)

        change                        name    price    volume     high     low
symbol
ATVI      2.57      ActivisionBlizzard,Inc   62.765   4795152   61.550   63.12
ADBE      1.33                    AdobeInc  374.190   1780244  367.205  374.31
AMD       0.18    AdvancedMicroDevices,Inc   53.895  44073229   53.540   54.84
ALXN      2.67  AlexionPharmaceuticals,Inc  105.200   1940834  101.570  105.20
ALGN      3.55         AlignTechnology,Inc  273.855    764027  265.815  276.05