In [1]:
## Tim Day
## 862016623
## Team JellyBean

from yahoofinancials import YahooFinancials
import pandas as pd
import json

In [2]:
# list all ticker symbols plus index symbol (ndx): 103 + 1
names_ndx_df = pd.read_csv('./data_files/stock_name.txt')

# get stock names from txt file
f = open('./data_files/stock_name.txt', 'r')
stocks_list = f.read().splitlines()
f.close()

# choose stocks
yf_nasdaq_104 = YahooFinancials(stocks_list)
#yf_nasdaq_104 = YahooFinancials(['AAL','AAPL','ADBE'])

# pull data from API
#stock_data = yf_nasdaq_104.get_stock_price_data()
#stock_data = yf_nasdaq_104.get_summary_data()
stock_data = yf_nasdaq_104.get_historical_price_data('2020-1-12','2020-2-12','daily')

# save json stock data
with open('./data_files/yf_nasdaq_104.json', 'w') as outfile:
    json.dump(stock_data, outfile)

# read json file into dataframe and transpose rows/cols
df = pd.read_json('./data_files/yf_nasdaq_104.json').T

# save a csv version of stock data
df.to_csv('./data_files/yf_nasdaq_104.csv')

df.head(5)

,eventsData,firstTradeDate,currency,instrumentType,timeZone,prices,isPending,id
AAL,"{'dividends': {'2020-02-04': {'amount': 0.1, '...","{'formatted_date': '2005-09-27', 'date': 11278...",USD,EQUITY,{'gmtOffset': -18000},"[{'date': 1578925800, 'high': 27.5300006866455...",NaN,NaN
AAPL,"{'dividends': {'2020-02-07': {'amount': 0.77, ...","{'formatted_date': '1980-12-12', 'date': 34545...",USD,EQUITY,{'gmtOffset': -18000},"[{'date': 1578925800, 'high': 317.070007324218...",NaN,NaN
ADBE,{},"{'formatted_date': '1986-08-13', 'date': 52430...",USD,EQUITY,{'gmtOffset': -18000},"[{'date': 1578925800, 'high': 345.730010986328...",NaN,NaN
ADI,{},"{'formatted_date': '1980-03-17', 'date': 32213...",USD,EQUITY,{'gmtOffset': -18000},"[{'date': 1578925800, 'high': 119.639999389648...",NaN,NaN
ADP,{},"{'formatted_date': '1980-03-17', 'date': 32213...",USD,EQUITY,{'gmtOffset': -18000},"[{'date': 1578925800, 'high': 172.470001220703...",NaN,NaN